# Generated by Django 5.0 on 2026-07-25 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the country",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "iso_code_3",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-3 country code",
                        max_length=3,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        db_index=True,
                        help_text="Full country name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("AF", "Africa"),
                            ("AS", "Asia"),
                            ("EU", "Europe"),
                            ("NA", "North America"),
                            ("SA", "South America"),
                            ("OC", "Oceania"),
                            ("AN", "Antarctica"),
                        ],
                        db_index=True,
                        help_text="Continent where the country is located",
                        max_length=2,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="Approximate center latitude coordinate",
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="Approximate center longitude coordinate",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the country record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the country record was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "country",
                "ordering": ["country_name"],
                "indexes": [
                    models.Index(
                        fields=["country_name"], name="country_country_252656_idx"
                    ),
                    models.Index(
                        fields=["iso_code"], name="country_iso_cod_d79cdb_idx"
                    ),
                    models.Index(
                        fields=["continent"], name="country_contine_f24fa2_idx"
                    ),
                    models.Index(
                        fields=["iso_code", "country_name"],
                        name="country_iso_cod_bdb894_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the city",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        db_index=True, help_text="Name of the city", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        db_index=True,
                        help_text="Geographic latitude coordinate in decimal degrees",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        db_index=True,
                        help_text="Geographic longitude coordinate in decimal degrees",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, help_text="City population", null=True
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="Timezone identifier (e.g., 'America/New_York')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the city record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the city record was last updated",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country where the city is located",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="graph_engine.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "city",
                "ordering": ["city_name"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the dataset",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dataset_name",
                    models.CharField(
                        db_index=True, help_text="Name of the dataset", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the dataset purpose and contents",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="synthetic",
                        help_text="Source of the data",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        db_index=True,
                        help_text="Dataset version following semantic versioning",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the dataset was created",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the dataset",
                        max_length=20,
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of records in the dataset"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration used for dataset generation",
                    ),
                ),
                (
                    "random_seed",
                    models.IntegerField(
                        blank=True,
                        help_text="Random seed used for reproducibility",
                        null=True,
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics about the dataset content",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="Checksum for data integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the dataset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasets",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
                "db_table": "dataset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the transaction",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "packet_count",
                    models.PositiveIntegerField(
                        help_text="Number of packets in the transaction"
                    ),
                ),
                (
                    "packet_size",
                    models.PositiveIntegerField(
                        default=1500, help_text="Average packet size in bytes"
                    ),
                ),
                (
                    "bandwidth",
                    models.FloatField(help_text="Bandwidth used in bytes per second"),
                ),
                (
                    "latency",
                    models.FloatField(help_text="Network latency in milliseconds"),
                ),
                (
                    "duration",
                    models.FloatField(
                        default=0.0, help_text="Connection duration in seconds"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HTTP", "HTTP"),
                            ("HTTPS", "HTTPS"),
                            ("SSH", "SSH"),
                            ("FTP", "FTP"),
                            ("SMTP", "SMTP"),
                            ("DNS", "DNS"),
                            ("TCP", "TCP"),
                            ("UDP", "UDP"),
                            ("ICMP", "ICMP"),
                            ("MQTT", "MQTT"),
                            ("WEBSOCKET", "WebSocket"),
                        ],
                        default="HTTPS",
                        help_text="Network protocol used",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp of the transaction"
                    ),
                ),
                (
                    "is_anomaly",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this transaction is an anomaly",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("P2P", "Peer-to-Peer"),
                            ("CLIENT_SERVER", "Client-Server"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="CLIENT_SERVER",
                        help_text="Type of connection",
                        max_length=20,
                    ),
                ),
                (
                    "encryption",
                    models.BooleanField(
                        default=False, help_text="Whether encryption was used"
                    ),
                ),
                (
                    "risk_label",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        help_text="Risk classification label",
                        max_length=10,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        help_text="Dataset this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="graph_engine.dataset",
                    ),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        help_text="Destination city of the transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transactions",
                        to="graph_engine.city",
                    ),
                ),
                (
                    "source_city",
                    models.ForeignKey(
                        help_text="Source city of the transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transactions",
                        to="graph_engine.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transaction",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["country"], name="city_country_b7fb66_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["city_name"], name="city_city_na_7e5e8f_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["latitude", "longitude"], name="city_latitud_f4e024_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country", "city_name"], name="city_country_f67c93_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="valid_longitude",
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["version"], name="dataset_version_9edd8a_idx"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["status"], name="dataset_status_2e4214_idx"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["created_at"], name="dataset_created_e01069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["status", "created_at"], name="dataset_status_61d381_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataset",
            unique_together={("dataset_name", "version")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["dataset"], name="transaction_dataset_9cf079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["timestamp"], name="transaction_timesta_97addc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["source_city"], name="transaction_source__f22dfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["destination_city"], name="transaction_destina_73ded2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_anomaly"], name="transaction_is_anom_464005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["dataset", "timestamp"], name="transaction_dataset_77b281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["source_city", "destination_city"],
                name="transaction_source__e1935b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("packet_count__gt", 0)), name="positive_packet_count"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("bandwidth__gte", 0)), name="positive_bandwidth"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("latency__gte", 0)), name="positive_latency"
            ),
        ),
    ]
