# Generated by Django 5.0 on 2026-07-26 16:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(db_index=True, max_length=2, unique=True),
                ),
                (
                    "iso_code_3",
                    models.CharField(
                        blank=True, db_index=True, max_length=3, null=True, unique=True
                    ),
                ),
                (
                    "country_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("AF", "Africa"),
                            ("AS", "Asia"),
                            ("EU", "Europe"),
                            ("NA", "North America"),
                            ("SA", "South America"),
                            ("OC", "Oceania"),
                            ("AN", "Antarctica"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "db_table": "country",
                "ordering": ["country_name"],
                "indexes": [
                    models.Index(fields=["country_name"], name="idx_country_name"),
                    models.Index(fields=["iso_code"], name="idx_country_iso_code"),
                    models.Index(fields=["continent"], name="idx_country_continent"),
                    models.Index(
                        fields=["iso_code", "country_name"], name="idx_country_iso_name"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("city_name", models.CharField(db_index=True, max_length=100)),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="graph_engine.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "db_table": "city",
                "ordering": ["city_name"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dataset_name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("real", "Real"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="synthetic",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(db_index=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("record_count", models.IntegerField(db_index=True, default=0)),
                ("random_seed", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasets",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "dataset",
                "verbose_name_plural": "datasets",
                "db_table": "dataset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("packet_count", models.IntegerField()),
                ("packet_size", models.IntegerField(db_index=True, default=1500)),
                ("bandwidth", models.FloatField(db_index=True)),
                ("latency", models.FloatField(db_index=True)),
                ("duration", models.FloatField(default=0.0)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HTTP", "Http"),
                            ("HTTPS", "Https"),
                            ("SSH", "Ssh"),
                            ("FTP", "Ftp"),
                            ("SMTP", "Smtp"),
                            ("DNS", "Dns"),
                            ("TCP", "Tcp"),
                            ("UDP", "Udp"),
                            ("ICMP", "Icmp"),
                        ],
                        db_index=True,
                        default="HTTPS",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("is_anomaly", models.BooleanField(db_index=True, default=False)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("CLIENT_SERVER", "Client Server"),
                            ("PEER_TO_PEER", "Peer To Peer"),
                            ("SERVER_TO_SERVER", "Server To Server"),
                            ("IOT", "Iot"),
                            ("CDN", "Cdn"),
                        ],
                        default="CLIENT_SERVER",
                        max_length=20,
                    ),
                ),
                ("encryption", models.BooleanField(default=False)),
                (
                    "risk_label",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="graph_engine.dataset",
                    ),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transactions",
                        to="graph_engine.city",
                    ),
                ),
                (
                    "source_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transactions",
                        to="graph_engine.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "db_table": "transaction",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["country"], name="idx_city_country"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["city_name"], name="idx_city_name"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["latitude", "longitude"], name="idx_city_coordinates"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country", "city_name"], name="idx_city_country_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="valid_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("population__gte", 0)), name="positive_population"
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["version"], name="idx_dataset_version"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["status"], name="idx_dataset_status"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["created_at"], name="idx_dataset_created_at"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["status", "created_at"], name="idx_dataset_status_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="dataset",
            constraint=models.CheckConstraint(
                check=models.Q(("record_count__gte", 0)),
                name="non_negative_record_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataset",
            constraint=models.CheckConstraint(
                check=models.Q(("version__regex", "^\\d+\\.\\d+\\.\\d+$")),
                name="valid_version_format",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataset",
            unique_together={("dataset_name", "version")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["dataset"], name="idx_transaction_dataset"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["timestamp"], name="idx_transaction_timestamp"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["source_city"], name="idx_transaction_source"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["destination_city"], name="idx_transaction_destination"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_anomaly"], name="idx_transaction_is_anomaly"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["dataset", "timestamp"], name="idx_trx_dst_ts"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["source_city", "destination_city"],
                name="idx_transaction_source_dest",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("packet_count__gt", 0)), name="positive_packet_count"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("bandwidth__gte", 0)), name="non_negative_bandwidth"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("latency__gte", 0)), name="non_negative_latency"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("source_city", models.F("id")), _negated=True),
                name="source_not_destination",
            ),
        ),
    ]
